version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./50x.html:/usr/share/nginx/html/50x.html:ro
    ports:
      - "80:80"
